### ISSUE TITLE
关于域名连通性检测结果的问题

### ISSUE THREAD

**Issue by MilkTea0329** [cokice/List-of-genshin-University#98]
原神电力大学.com，我刚才处理好了301跳转失败的问题，目前已经可以成功跳转，但是项目页中这个域名的状态仍为连接失败，请问这个状态多久之后才会刷新呀？

**Comment by CarlGao4** [comment]
大约每天8:30左右

**Comment by CarlGao4** [comment]
@cokice 建议升级一下，提高刷新频率（每天两次）

<details>
  <summary>update_status.yml</summary>

```yaml
name: Update Status
run-name: Update Status

on:
  workflow_dispatch: 
    inputs:
      no_skip_edu:
        description: 'Do not skip edu domains'
        required: true
        type: 'boolean'
        default: false
      count_only:
        description: 'Only count the number of domains, do not verify'
        required: true
        type: 'boolean'
        default: false
  schedule:
    - cron: '30 11,23 * * *'
  push:
    branches:
      - main
      - master
    paths: 
      - 'README.md'
      - '.github/workflows/update_status.yml'
      - 'verify-url.py'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  update_status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dnspython requests pypinyin

      - name: Prepare Proxy
        run: |
          echo -e "${{ secrets.PROXY }}" >> proxies.txt

      - name: Update status
        run: python3 verify-url.py
        env:
          NO_SKIP_EDU: ${{ github.event.inputs.no_skip_edu && '1' || '0' }}
          COUNT_ONLY: ${{ github.event.inputs.count_only && '1' || '0' }}

      - name: Revert Proxy
        run: |
          git checkout proxies.txt
      
      - name: Commit and push
        uses: actions4git/add-commit-push@v1
        with:
          commit-message: Update status
        continue-on-error: true

```

</details>
